<?php $profile = $profile ?: new \GuildUser\Model\Profile() ?>
<div id="contentbg">
	<div id="contentblank">
		<div id="content">
			
			<div id="contentwide" class="fleft">
<div>
<?php echo $this->gravatar($this->zfcUserIdentity()->getEmail()) ?>
שלום, <?php echo $this->zfcUserIdentity()->getDisplayName() ?>! <a href="<?php echo $this->url('zfcuser/logout') ?>">[התנתק]</a>
</div>

<div id="tabs">
	<ul class="tabs">
        <li class="tab">פרטים אישיים</li>
        <li class="tab">משחקים</li>
        <li class="tab">סביבה וסיגנון</li>
        <li class="tab">תכונות</li>
    </ul>
	<div class="tabs-container">
		<div id="personal-details-box" class="tab-content content-box">
			<h3>פרטים אישיים</h3>
			<?php
$personal->prepare();
echo $this->form()->openTag($personal);

?>
			<dl class="zend_form">
				<dd><?php echo $this->formTextarea($personal->get('bio')->setAttribute('id', 'personal-bio-element')) . $this->formElementErrors($personal->get('bio')); ?></dd>
				<dt><?php echo $this->formLabel($personal->get('full_name')); ?></dt>
				<dd><?php echo $this->formInput($personal->get('full_name')) . $this->formElementErrors($personal->get('full_name')); ?></dd>
				<dt><?php echo $this->formLabel($personal->get('display_name')); ?></dt>
				<dd><?php echo $this->formInput($personal->get('display_name')) . $this->formElementErrors($personal->get('display_name')); ?></dd>
				<dt><?php echo $this->formLabel($personal->get('email')); ?></dt>
				<dd><?php echo $this->formInput($personal->get('email')) . $this->formElementErrors($personal->get('email')); ?></dd>
				<dt><?php echo $this->formLabel($personal->get('lfg')); ?></dt>
				<dd><?php echo $this->formRadio($personal->get('lfg')) . $this->formElementErrors($personal->get('lfg')); ?></dd>
				<dt><?php echo $this->formLabel($personal->get('gender')); ?></dt>
				<dd><?php echo $this->formRadio($personal->get('gender')) . $this->formElementErrors($personal->get('gender')); ?></dd>
				<dd><?php echo $this->formInput($personal->get('personal-submit')->setAttribute('id','personal-submit')) ?></dd>
			</dl>
			<?php echo $this->form()->closeTag(); ?>
			<div id="result"></div>
		</div>

		<div id="registered-games-box" class="tab-content content-box">
			<h3 style="display: inline">משחקים</h3>&nbsp;[<a id="registered-games-select-all" href="javascript:void(0)">סמן הכול</a>]&nbsp;[<a id="registered-games-clear-all" href="javascript:void(0)">נקה בחירה</a>]
			<div>
<?php foreach ($games as $game): ?>
<?php	echo $this->gameIcon($game, isset($assignedGames[$game['game_id']]) && intval($assignedGames[$game['game_id']]['enabled'])) ?>
<?php endforeach ?>
			</div>
		</div>

		<div class="tab-content content-box">
			<h3>סביבה וסיגנון</h3>
			<ul class="no-bullets-list multiple-select form-field">
				<li><input type="checkbox" id="location[gush-dan]"/><label for="location[gush-dan]">גוש דן</label></li>
				<li><input type="checkbox" id="location[hasharon]" /><label for="location[hasharon]">השרון</label></li>
				<li><input type="checkbox" id="location[hashfela]" /><label for="location[hashfela]">השפלה</label></li>
				<li><input type="checkbox" id="location[abroad]" /><label for="location[abroad]">חו"ל</label></li>
			</ul>
		</div>

		<div id="attributes-editor" class="tab-content content-box">
			<h3>התכונות שלי</h3>

			<div id="attributes-form-box" class="content-box">
				<div id="attribute-info-box" class="content-box fright">
<?php foreach ($tooltips as $identifier => $attribute) : ?>
<?php	foreach ($attribute['scores'] as $value => $score) : ?>
					<div id="attribute_<?php echo $identifier ?>-<?php echo $value ?>" class="attribute-info tooltip">
						<div class="tooltip-content">
							<h3><?php echo $attribute['headline'] ?>: <?php echo $value ?></h3>
							<blockquote><?php echo $score['quote'] ?></blockquote>
							<p><?php echo $score['text'] ?></p>
						</div>
					</div>
<?php	endforeach ?>
<?php endforeach ?>
				</div>
				<ul id="attributes-form-list" class="form-field no-bullets-list">
					<li id="attribute-humour-item"><label>הומור</label>
						<?php echo $this->slider('humour') ?>
					</li>
					<li id="attribute-teamplay-item"><label>חברותי</label>
						<?php echo $this->slider('teamplay') ?>
					</li>
					<li id="attribute-mobility-item"><label>ניידות</label>
						<?php echo $this->slider('mobility') ?>
					</li>
					<li id="attribute-hospitality-item"><label>אירוח</label>
						<?php echo $this->slider('hospitality') ?>
					</li>
					<li id="attribute-strictness-item"><label>קפדנות</label>
						<?php echo $this->slider('strictness') ?>
					</li>
					<?php
$attributesForm->prepare();
echo $this->form()->openTag($attributesForm);
?>
			<dl class="zend_form">
			<?php foreach ($attributesForm->getElements() as $element) { ?>
				<?php if ($element->getAttribute('label') != null) { ?>
				<dt><?php echo $this->formLabel($element); ?></dt>
				<?php } ?>
				<dd><?php echo $this->formInput($element) . $this->formElementErrors($element); ?></dd>
			<?php } ?>
			</dl>
			<?php echo $this->form()->closeTag(); ?>
				</ul>
			</div>
		</div>
	</div>
</div>

<script type="text/javascript" >

function toggleUserGame(enable) {
	// collect all checkboxes
	var checkboxes = $$('.game_selector_input');
	var games = {};
	checkboxes.each(function(item){
		// collect all gameids
		games[item.value] = enable ? 1 : 0;
	});
	// disable checkboxes
	checkboxes.set('disabled', true);
	checkboxes.set('checked', enable);
	// send json request
	new Request.JSON({
		url: '/guilduser/setgames',
		onComplete: function() {
			// enable checkboxes
			this.set('disabled', false);
		}.bind(checkboxes)
	}).post({'games': games});
}
// ON LOAD 
window.addEvent('domready', function() {
	
	$('registered-games-select-all').addEvent('click', toggleUserGame.pass(true));
	
	$('registered-games-clear-all').addEvent('click', toggleUserGame.pass(false));
	
	$$('input.game_selector_input').addEvent('click', function(event){
		var checkBox = event.target;
		var gameId = checkBox.value;
		var enable = checkBox.checked ? 1 : 0;

		this.set('disabled', true);
		new Request.JSON({
			url: '/guilduser/setgame',
			onComplete: function() {
				this.set('disabled', false);
			}.bind(this)
		}).post({'gameId': gameId, 'enable': enable});
		event.stopPropagation(true);
	});

	new Form.Request($('attributes-form'), null, {
		onSend: function(){
			$('attributes-attributessubmit').set('value', 'שומר תכונות...').set('disabled', true);
		},
		onComplete: function(resultNode, textNodes, args, responseText){
			$('attributes-attributessubmit').set('value', 'שמור תכונות').set('disabled', false);
		},
		requestOptions: {
			spinnerTarget: $('attributessubmit-element')
		},
		resetForm: false
	});

	new Form.Request($('personal-form'), null, {
		onSend: function(){
			$('personal-submit').set('value', 'שומר פרטים אישיים...').set('disabled', true);
		},
		onComplete: function(resultNode, textNodes, args, responseText){
			$('personal-submit').set('value', 'שמור פרטים אישיים').set('disabled', false);
			var response = eval("(" + responseText + ")");
			if (response.success) {
				
			}
		},
		requestOptions: {
			spinnerTarget: $('personalsubmit-element')
		},
		resetForm: false
	});

	
        var tabPane = new TabPane('tabs', {contentSelector: '.tab-content'}, function() {
			var showTab = window.location.hash.match(/tab=(\d+)/);
			return showTab ? showTab[1].toInt() : 0;
		});

        tabPane.addEvent('change', function(what){
			window.location.hash = 'tab='+what;
// @todo Why is this needed?
			// initialise the sliders if the editor is visible and was not previously initialised
			if ($('attributes-editor').isVisible() && (! $('attributes-editor').initialised)) {
				var attributes = {
					
					humour: <?php echo intval($profile->getHumour()) ?>,
					teamplay: <?php echo intval($profile->getTeamplay()) ?>,
					mobility: <?php echo intval($profile->getMobility()) ?>,
					hospitality: <?php echo intval($profile->getHospitality()) ?>,
					strictness: <?php echo intval($profile->getStrictness()) ?>
					
				};

				Object.each(attributes,
					function(score, attribute) {
						new Slider($$('#attribute-'+ attribute +'-item .slider_gutter_i')[0],
												$$('#attribute-'+ attribute +'-item .knob')[0],
												$$('#attribute-'+ attribute +'-item img.slider_bkg')[0],{
							start: 1,
							end: 5,
							offset:0,
							snap:true, 
							numsteps:4,
							onChange: function(pos){
								$$('.attribute-info').removeClass('active');
								if ($('attribute_'+ attribute +'-'+pos)) {
									$('attribute_'+ attribute +'-'+pos).addClass('active');
								}

								if ($('attributes-'+ attribute)) {
									$('attributes-'+ attribute).value = pos;
								}

							}
						}, null).setMin(score);
				});
				
				$('attributes-editor').initialised = true;
	        }
        });
		/// must be fired so that tab init happens
		if (window.location.hash.match(/tab=(\d+)/)) {
			tabPane.fireEvent('change', window.location.hash.match(/tab=(\d+)/)[1].toInt());
		}
});


</script>
			</div>
			<div id="contentright" class="fright">
				side panel
			</div>
		</div>
	</div>
</div>
				

