<?php
$users = $users ?: array();
$profiles = $profiles ?: array()
?>
<script type="text/javascript">
window.addEvent('domready', function () {
	
	$$('ul.attributes-mini-list li.humour').addEvent('mouseover', function() {
    	ToolTip.instance(this, {
    		relativeTo: this.id,
    		autohide: true,
    		hideDelay: 150,
    		position: {position: 'centerBottom', edge: 'top'}
    	}, document.id('attribute-humour-tooltip-2')).show();
    });


});
</script>

<div id="attribute-humour-tooltip-2" class="tooltip-content"><h3>דירוג הומור: 2</h3>
	<blockquote>גנום, טרול ושני גובלינים נכנסים ל... רגע, לא, מההתחלה</blockquote>
	<p>אתה לא מצחיק אבל כנראה גם לא מדכא. משחקים איתך הם משעשעים, כל עוד הכנת את הבדיחות מראש ועשית חזרות בבית.</p>
</div>

<div id="contentbg">
	<div id="contentblank">
		<div id="content">
			
			<div id="contentwide" class="fleft">
			<table>
			<thead>
			<tr><th><input type="checkbox" /></th>
			<th>שם</th><th>תכונות</th><th>גיל</th></tr>
			</thead>
			<tbody>
<?php foreach ($users as $user) :/* @var $profile \ZfcUser\Model\User */ ?>
			<tr><th><input type="checkbox" /></th>
			<td><a href="<?php echo $this->url('default', array('controller' => 'index', 'action' => 'sheet'))?>?<?php echo http_build_query(array('id' => $user->getUserId())) ?>"><?php echo $user->getDisplayName() ?></a></td>
<?php	if (isset($profiles[$user->getUserId()])) : ?>
<?php		$profile = $profiles[$user->getUserId()]; ?>
			<td><ul class="attributes-mini-list">
				<li class="humour"><?php echo $profile->getHumour(); ?></li>
				<li class="teamplay"><?php echo $profile->getTeamplay(); ?></li>
				<li class="mobility"><?php echo $profile->getMobility(); ?></li>
				<li class="hospitality"><?php echo $profile->getHospitality(); ?></li>
				<li class="strictness"><?php echo $profile->getStrictness(); ?></li>
			</ul></td>
			<td><?php echo floor((time() - strtotime($profile->getBirthDate()))/60/60/24/365) ?></td></tr>
<?php	else: ?>
			<td>לא הוגדרו תכונות</td>
			<td></td>
<?php	endif ?>
<?php endforeach ?>
			</tbody>
			</table>
			</div>
			
			<div id="contentright" class="fright">
			<div>Available filters</div>
			<div>Used filters</div>
			</div>
		</div>
	</div>
</div>