<?php $row = $row ?: new \ZfcUser\Model\User() ?>
<?php $games = $games ?: array() ?>
<?php $profile = $profile ?: array() ?>
<script type="text/javascript">
window.addEvent('domready', function () {
    var duration = 300,
    links = $$('div#slider-nav a'),
    tab = new Carousel.Extra({
	    container: 'slider',
	    scroll: 1,
	    circular: true,
	    current: 3,
	    previous: links.shift(),
	    next: links.pop(),
	    tabs: links,
	    mode: 'horizontal',
	    autostart: false,
	    activeClass: 'selected',
	    fx: {
	    	duration: duration
	    }
    });

    document.id('attribute-details-humor').addEvent('mouseover', function() {
    	ToolTip.instance(this, {
    		relativeTo: this.id,
    		autohide: true,
    		hideDelay: 150,
    		position: {position: 'centerLeft', edge: 'right'}
    	}, document.id('attribute-humour-tooltip-2')).show();
    });

    document.id('attribute-details-teamplay').addEvent('mouseover', function() {
    	ToolTip.instance(this, {
    		relativeTo: this.id,
    		autohide: true,
    		hideDelay: 150,
    		position: {position: 'centerLeft', edge: 'right'}
    	}, document.id('attribute-teamplay-tooltip-3')).show();
    });

    document.id('attribute-details-leadership').addEvent('mouseover', function() {
    	ToolTip.instance(this, {
    		relativeTo: this.id,
    		autohide: true,
    		hideDelay: 150,
    		position: {position: 'centerLeft', edge: 'right'}
    	}, document.id('attribute-leadership-tooltip-3')).show();
    });
    
    document.id('attribute-details-mobility').addEvent('mouseover', function() {
    	ToolTip.instance(this, {
    		relativeTo: this.id,
    		autohide: true,
    		hideDelay: 150,
    		position: {position: 'centerLeft', edge: 'right'}
    	}, document.id('attribute-mobility-tooltip-3')).show();
    });

    document.id('attribute-details-focus').addEvent('mouseover', function() {
    	ToolTip.instance(this, {
    		relativeTo: this.id,
    		autohide: true,
    		hideDelay: 150,
    		position: {position: 'centerLeft', edge: 'right'}
    	}, document.id('attribute-focus-tooltip-3')).show();
    });

    document.id('attribute-details-hospitality').addEvent('mouseover', function() {
    	ToolTip.instance(this, {
    		relativeTo: this.id,
    		autohide: true,
    		hideDelay: 150,
    		position: {position: 'centerLeft', edge: 'right'}
    	}, document.id('attribute-hospitality-tooltip-5')).show();
    });

    document.id('attribute-details-strictness').addEvent('mouseover', function() {
    	ToolTip.instance(this, {
    		relativeTo: this.id,
    		autohide: true,
    		hideDelay: 150,
    		position: {position: 'centerLeft', edge: 'right'}
    	}, document.id('attribute-strictness-tooltip-2')).show();
    });

<?php foreach (array('crunch', 'lore', 'gm') as $ability) : ?>
<?php 	foreach ($games as $game) :?>
    document.id('ability-details-<?php echo $ability ?>-<?php echo $game['game_id']?>').addEvent('mouseover', function() {
    	ToolTip.instance(this, {
    		relativeTo: this.id,
    		autohide: true,
    		hideDelay: 150,
    		position: {position: 'centerLeft', edge: 'right'}
    	}, document.id('ability-details-<?php echo $ability ?>-tooltip-<?php echo $game["ability_$ability"]?>')).show();
    });
<?php 	endforeach; ?>
<?php endforeach; ?>
});
</script>
<div id="ability-details-gm-tooltip-4" class="tooltip-content"><h3>דירוג מנחה: 4</h3>
	<blockquote>תנו לי לפתוח בפניכם את העולם שגדל אצלי בראש</blockquote>
	<p>הנחייה בוערת בעורקיך ומשחקים שבהם אינך מנחה הם רק הפסקות כדי ללמוד מטעויותיהם של אחרים.</p>
	<p>העולמות שלך מפורטים, הדמויות מגוונות ומהימנות והעלילות הן כמו ספר משובח.</p>
</div>
<div id="ability-details-gm-tooltip-2" class="tooltip-content"><h3>דירוג מנחה: 2</h3>
	<blockquote>די כבר להרוג לי את הרעים!</blockquote>
	<p>אתה חדש במשחק הזה, לא מנוסה בהנחייה או שפשוט אין לך כישרון...</p>
	<p>אתה יכול להעביר משחק אבל קצר כזה ושהדמויות לא יעשו משהו מפתיע</p>
</div>
<div id="ability-details-lore-tooltip-4" class="tooltip-content"><h3>דירוג ידע כללי: 4</h3>
	<blockquote>אז ככה: בשנת 3591 למניין האימפריה...</blockquote>
	<p>אתה תיעוד מהלך להיסטוריה, תרבויות וסיפורי העמים של עולם המשחק.</p>
	<p>אתה מסוגל לצטט טקסטים היסטוריים, נאומים מפורסמים ואנקדוטות איזוטריות מסיפורי הרקע של הדמויות בחבורה.</p>
</div>
<div id="ability-details-lore-tooltip-3" class="tooltip-content"><h3>דירוג ידע כללי: 3</h3>
	<blockquote>בספר הופיע משהו לגבי זה!</blockquote>
	<p>קראת בספרי המשחק או את סיפורי הרקע והספרים בכריכה רכה. אהבת, נהנית. זהו.</p>
	<p>באופן כללי אתה מכיר את עולם המשחק. אתה מכיר מקומות, שמות ומסוגל אולי גם להריץ קטעים על פרטים איזוטריים</p>
</div>
<div id="ability-details-lore-tooltip-1" class="tooltip-content"><h3>דירוג ידע כללי: 1</h3>
	<blockquote>זה יותר ממה שהייתי צריך לקרוא לבגרות בהיסטוריה!</blockquote>
	<p>חדש לחלוטין למשחק. אולי שמעת פעם תיאור קצר על מה המשחק באופן כללי</p>
	<p>יש לי המון מה לקרוא וכנראה שבמשחקים הראשונים אמציא כינויים מצחיקים לנפ"צים הראשיים</p>
</div>
<div id="ability-details-crunch-tooltip-3" class="tooltip-content"><h3>דירוג קראנץ': 3</h3>
	<blockquote>רגע, אני רק רוצה לוודא שלא שכחתי משהו</blockquote>
	<p>החוקים של המשחק מוכרים לך וייתכן שקראת יותר מספר השחקן הבסיסי.</p>
	<p>החישובים הבסיסיים ברורים לך אבל לפעמים אתה שוכח להוסיף את הבונוסים שלך.</p>
</div>
<div id="ability-details-crunch-tooltip-2" class="tooltip-content"><h3>דירוג קראנץ': 2</h3>
	<blockquote>אז כאילו לרשום את כל זה פה בדף?</blockquote>
	<p>קראת את ספר החוקים הבסיסי. טוב, את הפרקים עם התמונות של ה... דרקונים.</p>
	<p>אולי רק עיינת בספר ואתה זוכר פה ושם פרטים אבל הפרטים קצת מעורפלים. כנראה שתזדקק לעזרה במשחק עצמו</p>
</div>
<div id="ability-details-crunch-tooltip-1" class="tooltip-content"><h3>דירוג קראנץ': 1</h3>
	<blockquote>רגע, אני רק רוצה לוודא שלא שכחתי משהו</blockquote>
	<p>החוקים של המשחק מוכרים לך וייתכן שקראת יותר מספר השחקן הבסיסי.</p>
	<p>החישובים הבסיסיים ברורים לך אבל לפעמים אתה שוכח להוסיף את הבונוסים שלך.</p>
</div>
<div id="attribute-humour-tooltip-2" class="tooltip-content"><h3>דירוג הומור: 2</h3>
	<blockquote>גנום, טרול ושני גובלינים נכנסים ל... רגע, לא, מההתחלה</blockquote>
	<p>אתה לא מצחיק אבל כנראה גם לא מדכא. משחקים איתך הם משעשעים, כל עוד הכנת את הבדיחות מראש ועשית חזרות בבית.</p>
</div>
<div id="attribute-teamplay-tooltip-3" class="tooltip-content"><h3>חברותי דירוג: 3</h3>
	<blockquote>גנום, טרול ושני גובלינים נכנסים ל... רגע, לא, מההתחלה</blockquote>
	<p>אתה לא מצחיק אבל כנראה גם לא מדכא. משחקים איתך הם משעשעים, כל עוד הכנת את הבדיחות מראש ועשית חזרות בבית.</p>
</div>
<div id="attribute-leadership-tooltip-3" class="tooltip-content"><h3>דירוג מנהיגות: 3</h3>
	<blockquote>גנום, טרול ושני גובלינים נכנסים ל... רגע, לא, מההתחלה</blockquote>
	<p>אתה לא מצחיק אבל כנראה גם לא מדכא. משחקים איתך הם משעשעים, כל עוד הכנת את הבדיחות מראש ועשית חזרות בבית.</p>
</div>
<div id="attribute-mobility-tooltip-3" class="tooltip-content"><h3>דירוג ניידות: 3</h3>
	<blockquote>תרד, אני מגיע</blockquote>
	<p>אתה נייד וממונע. בין אם בכוחות קסומים, על הסוס של אבא או המכונית הפרטית,
	 אתה מסוגל להגיע לכל מקום המרחק סביר ואולי אף תיתן טרמפים עבור פיצוי הולם</p>
</div>
<div id="attribute-focus-tooltip-3" class="tooltip-content"><h3>דירוג מיקוד: 3</h3>
<blockquote>פגיעה! בואו נזרוק נזק ונדבר על סרטים!</blockquote>
<p>בשבילך המשחק הוא לא רק הזדמנות לזכות בניקוד דימיוני אלא גם הזדמנות לשוחח על ספרות, המכונית החדשה
והאפליקציה החדשה לאייפון, היא ממש מגניבה לא?</p>
</div>
<div id="attribute-hospitality-tooltip-5" class="tooltip-content"><h3>דירוג אירוח: 5</h3>
<blockquote>בואו! יש פיצה ביתית!</blockquote>
<p>אם היית יכול, היית עושה מינ/מקס למטבח והסלון שלך. כל משחק אצלך הוא חגיגה של אוכל, חברה ומשחק
עד השעות הקטנות של הלילה</p>
</div>
<div id="attribute-strictness-tooltip-2" class="tooltip-content"><h3>דירוג קפדנות: 2</h3>
<blockquote>המשחק נברא כדי שיהנו ממנו</blockquote>
<p> החוקים של המשחק והמנחה לא ממש חשובים לך - הם מצע מעניין לדיונים פילוסופיים אבל הם יכולים להישרף
לפני שתיתן להם לעכב לך את המשחק או לעצור את הדמות שלך מלעשות משהו שהיא רוצה.</p>
</div>
<div id="contentbg">
	<div id="contentblank">
		<div id="content">
			
			<div id="contentwide" class="fleft">
				<div class="column fleft content-box" >
					<h2>משחקים רשומים</h2>
					<div id="slider-nav" >
					<a href="#page-p">&laquo;</a>
<?php $panel = 1; foreach ($games as $game): ?>
					<a href="#<?php echo $panel++ ?>"><?php echo $game['game_name_short']?></a>&nbsp;
<?php endforeach;?>
					<a href="#page-p">&raquo;</a>
					</div>
					<div id="slider">
<?php $panel = 1; foreach ($games as $game): ?>
						<div class="panel">
							<div class="abilities-box content-box">
								<h2><?php echo $game['game_name']?></h2>
								<table class="abilities-table">
									<tbody>
										<tr>
											<td class="ability-name">קראנץ'</td>
											<td class="ability-value"><div class="value-bar" style="width:<?php echo ($game['ability_crunch'] / 5 * 100)?>%"></div></td>
											<td class="ability-details"><div id="ability-details-crunch-<?php echo $game['game_id']?>" class="ability-details-crunch icon"></div></td>
										</tr>
										<tr>
											<td class="ability-name">ידע כללי</td>
											<td class="ability-value"><div class="value-bar" style="width:<?php echo ($game['ability_lore'] / 5 * 100)?>%"></div></td>
											<td class="ability-details"><div id="ability-details-lore-<?php echo $game['game_id']?>" class="ability-details-lore icon"></div></td>
										</tr>
										<tr>
											<td class="ability-name">מנחה</td>
											<td class="ability-value"><div class="value-bar" style="width:<?php echo ($game['ability_gm'] / 5 * 100)?>%;"></div></td>
											<td class="ability-details"><div id="ability-details-gm-<?php echo $game['game_id']?>" class="ability-details-gm icon"></div></td>
										</tr>
									</tbody>
								</table>
							</div>
<?php if ($game['comments']) :?>
							<div class="comments-box content-box">
								<h3>הערות, סגנון משחק מועדף</h3>
								<div class="comments-internal">
<?php echo nl2br($game['comments']); ?>
								</div>
							</div>
<?php endif; ?>
						</div>
<?php endforeach;?>
					</div>
				</div>
					
				<div class="column fright">
					<h2>מידע אישי ותכונות</h2>
					<div id="personal-box" class="content-box">
						<div id="gravatar" class="fleft"><?php echo $this->gravatar($row->getEmail()); ?></div>
						<ul>
							<li><div><label>כינוי</label><div class="fright"><?php echo $row->getDisplayName() ?></div></div></li>
							<li><div><label>מין</label><div class="fright"><?php echo $profile['gender'] ?></div></div></li>
							<li><div><label>גיל</label><div class="fright"><?php echo floor((time() - strtotime($profile['birth_date']))/60/60/24/365) ?></div></div></li>
							<li><div><label>עדכון אחרון</label><div class="fright"><?php echo substr($row->getLastLogin(), 0, strpos($row->getLastLogin(), ' ')) ?></div></div></li>
						</ul>
					</div>
					
					<div id="attributes-box" class="content-box clear">
					<h3>תכונות</h3>
					<table class="attributes-table" style="width:100%">
						<tbody>
							<tr class="attribute-humour">
								<td class="attribute-name">הומור</td>
								<td class="attribute-value"><div  class="value-bar" style="width:<?php echo ($profile['humour'] / 5 * 100)?>%;"></div></td>
								<td class="attribute-details"><div id="attribute-details-humor" class="icon"></div>
									</td>
							</tr>
							<tr class="attribute-teamplay">
								<td class="attribute-name">חברותי</td>
								<td class="attribute-value"><div  class="value-bar" style="width:<?php echo ($profile['teamplay'] / 5 * 100)?>%;"></div></td>
								<td class="attribute-details"><div id="attribute-details-teamplay" class="icon"></div></td>
							</tr>
							<tr class="attribute-leadership">
								<td class="attribute-name">מנהיגות</td>
								<td class="attribute-value"><div  class="value-bar" style="width:<?php echo ($profile['leadership'] / 5 * 100)?>%;"></div></td>
								<td class="attribute-details"><div id="attribute-details-leadership" class="icon"></div></td>
							</tr>
							<tr class="attribute-mobility">
								<td class="attribute-name">ניידות</td>
								<td class="attribute-value"><div  class="value-bar" style="width:<?php echo ($profile['mobility'] / 5 * 100)?>%;"></div></td>
								<td class="attribute-details"><div id="attribute-details-mobility" class="icon"></div></td>
							</tr>
							<tr class="attribute-focus">
								<td class="attribute-name">מיקוד</td>
								<td class="attribute-value"><div  class="value-bar" style="width:<?php echo ($profile['focus'] / 5 * 100)?>%;"></div></td>
								<td class="attribute-details"><div id="attribute-details-focus" class="icon"></div>
									</td>
							</tr>
							<tr class="attribute-hospitality">
								<td class="attribute-name">אירוח</td>
								<td class="attribute-value"><div class="value-bar" style="width:<?php echo ($profile['hospitality'] / 5 * 100)?>%;"></div></td>
								<td class="attribute-details"><div id="attribute-details-hospitality" class="icon"></div>
									</td>
							</tr>
							<tr class="attribute-strictness">
								<td class="attribute-name">קפדנות</td>
								<td class="attribute-value"><div class="value-bar" style="width:<?php echo ($profile['strictness'] / 5 * 100)?>%;"></div></td>
								<td class="attribute-details"><div id="attribute-details-strictness" class="icon"></div>
									</td>
							</tr>
						</tbody>
					</table>
					</div>
					<div id="bio-box" class="content-box">
					<h3>כמה מילים על עצמי</h3>
					<div id="bio-text"><?php echo nl2br($profile['bio'])?></div>
				</div>
				</div>
				
			</div>
			
			<div id="contentright" class="fright">
				<div id="lfg-box" class="content-box">
				
				</div>
				
				
				<div id="locations-box" class="clear">
					<h3>מיקום רצוי למשחק</h3>
					<div id="location-hasharon" class="location">
						<label>השרון</label>
					</div>
					<div id="location-telaviv" class="location">
						<label>תל אביב</label>
					</div>
				</div>
				
				<div id="new-games" class="content-box">
					<h3>מוכן ללמוד משחקים חדשים</h3>
					<ul>
					<li>אימה</li>
					<li>גיבורי על</li>
					<li>חופשיטה</li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>
