<div id="contentbg">
	<div id="contentblank">
		<div id="content">
			
			<div id="contentwide" class="fleft">
				<div id="login">
					<div id="loginheading">
						<h4>הזדהה במערכת</h4>
						
						<?php

$form = $this->loginForm;

$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/login'));
$form->setAttribute('method', 'post');

echo $this->form()->openTag($form);

?>
<dl class="zend_form">
<?php echo $this->formElementErrors($form->get('identity')); ?>
<dt><?php echo $this->formLabel($form->get('identity')); ?></dt>
<dd><?php echo $this->formInput($form->get('identity')); ?></dd>

<dt><?php echo $this->formLabel($form->get('credential')); ?></dt>
<dd><?php
echo $this->formInput($form->get('credential'));
?></dd>

<dd><?php
echo $this->formInput($form->get('csrf'));
echo $this->formInput($form->get('submit'));
?></dd>

</dl>

<?php echo $this->form()->closeTag(); ?>
						<div>
							לא רשום עדיין? לא נורא! <a href="<?php echo $this->url('zfcuser/register') ?>">הירשם כאן!</a>
						</div>
					</div>
				</div>
			</div>
			<div id="contentright" class="fright">
				side panel
			</div>
		</div>
	</div>
</div>