<?php 
$this->headTitle()->setSeparator(' - ')
                  ->setAutoEscape(false);

$basePath = $this->basePath();
$this->headLink()->prependStylesheet($basePath . '/css/bootstrap.min.rtl.css')
                 ->prependStylesheet($basePath . '/css/style.css')
                 ->prependStylesheet($basePath . '/css/bootstrap-responsive.min.css');

$this->headLink(array(
            'rel'  => 'shortcut icon',
            'type' => 'image/vnd.microsoft.icon',
            'href' => $basePath . '/images/favicon.ico',
        ));

// HTML5 shim, for IE6-8 support of HTML elements
$this->headScript()->appendFile($basePath . '/js/html5.js', 'text/javascript', 
    array('conditional' => 'lt IE9',));

echo $this->doctype();
?>

<html lang="en">
  <head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('ZF2 Skeleton Application') ?>

    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

    <!-- Le styles -->
    <?php echo $this->headLink() ?>
    
    <!-- Scripts -->
    <?php echo $this->headScript() ?>

  </head>

  <body>
<div id="headerbg">
	<div id="headerblank">
		<div id="header">
			<div id="menu">
				<ul>
					<li><a href="<?php echo $this->url('home') ?>" class="menu">דף הבית</a></li>
					<li><a href="<?php echo $this->url('home') ?>" class="menu">חיפוש</a></li>
					<li><a href="<?php echo $this->url('home') ?>" class="menu">פרופיל אישי</a></li>
					<li><a href="#" class="menu">משחקים</a></li>
					<li><a href="#" class="menu">מי אנחנו</a></li>
					<li><a href="<?php echo $this->url('home') ?>" class="menu">התנתק</a></li>
				</ul>
			</div>
<?php /*if (isset($loginForm)): ?>
<?php 	if ($this->edpUserIdentity()): ?>
			<div id="login">
				<div id="logintxtblank">
					<div id="loginheading">
						<h4>משתמש נוכחי</h4>
					</div>
					<div>
<?php 	echo $this->gravatar($this->edpUserIdentity()->getEmail()) ?>
שלום, <?php echo $this->edpUserIdentity()->getDisplayName() ?>! <a href="<?php echo $this->url('edpuser/logout') ?>">[התנתק]</a>
					</div>
				</div>
			</div>
<?php 	else:*/?>
			<div id="login">
				<div id="logintxtblank">
					<div id="loginheading">
						<h4>הזדהה במערכת</h4>
					</div>
				<?php //echo $loginForm->setAction($this->url('edpuser/login'))->setView($this); ?>
					<div id="member">לא רשום? לא נורא! </div>
					<div id="register"><a href="<?php echo $this->url('home') ?>">הירשם כאן!</a></div>
				</div>
			</div>
<?php /* 	endif ?>
<?php endif*/ ?>
		</div>
	</div>
</div>
<?php echo $this->content; ?>
<div id="footerbg">
	<div id="footerblank">
		<div id="footer">
			<div id="footerbox">
				<div class="footerheading"><h4>Tempus</h4></div>
				<div class="footertxt">Donec posuere bibendum erat.	commodo consectetuer tellus. Ut ut tellus eget</div>
				<div class="footerbutton"><a href="#" class="button">read more</a></div>
			</div>
			<div id="footermid"><div class="footerheading"><h4>Neque</h4></div>
			<div class="footertxt">Neque nisl porttitor dolor, ut posuere nibh lectus vel pede. Nam non elit.</div>
			<div class="footerbutton"><a href="#" class="button">read more</a></div>
			</div>
			<div id="footerlast">
				<div class="footerheading">
					<h4>Curabitur</h4>
				</div>
				<div class="footertxt">Eque nisl porttitor dolor, ut posuere nibh lectus vel pede. Nam non elit. </div>
				<div class="footerbutton"><a href="#" class="button">read more</a></div>
			</div>
			<div id="footerlinks"><a href="#" class="footerlinks">Home</a> | <a href="#" class="footerlinks">About Us</a> | <a href="#" class="footerlinks">Support</a> | <a href="#" class="footerlinks">Forum</a> | <a href="#" class="footerlinks">Development</a> | <a href="#" class="footerlinks">Conact Us</a></div>
		</div>
	</div>
</div>
</body>
  
</html>
