<div id="contentbg">
	<div id="contentblank">
		<div id="content"><div class="inner_copy"><div class="inner_copy">All <a href="http://www.magentothemesworld.com" title="Best Magento Templates">premium Magento themes</a> at magentothemesworld.com!</div></div>
			<div id="contentleft">

				<div id="leftheading">
					<h4>עדכוני קהילה</h4>
				</div>
				<div class="lefttxtblank">
					<div class="lefticon">16</div>
					<div class="leftboldtxtblank">
						<div class="leftboldtxt">Pulvinar interdum ...</div>

						<div class="lefttxt">By Jack Son | 11:55 AM</div>
					</div>
					<div class="leftnormaltxt">Etiam auctor nisl adipiscing sem.	erat urna fringilla sit ametvestibulum.</div>
					<div class="morebutton"><a href="#" class="more">להמשך... </a></div>
				</div>
				<div class="lefttxtblank02">
					<div class="lefticon">16</div>

					<div class="leftboldtxtblank">
						<div class="leftboldtxt">Aulvinar gnterdum ...</div>
						<div class="lefttxt">By Jack Son | 11:55 AM</div>
					</div>
					<div class="leftnormaltxt">Stiam auctor nisl adipiscing sem.	erat urna fringilla sit ametvestibulum.</div>
					<div class="morebutton"><a href="#" class="more">להמשך... </a></div>
				</div>

				<div class="lefttxtblank02">
					<div class="lefticon">16</div>
					<div class="leftboldtxtblank">
						<div class="leftboldtxt">Qulvinar snterdum ...</div>
						<div class="lefttxt">By Jack Son | 11:55 AM</div>
					</div>
					<div class="leftnormaltxt">Etiam auctor nisl adipiscing sem.	erat urna fringilla sit ametvestibulum.</div>

					<div class="morebutton"><a href="#" class="more">להמשך... </a></div>
				</div>
				<div id="leftnavheading">
					<h4>לינקים</h4>
				</div>
				<div id="leftnav">
					<ul>
						<li><a href="#" class="leftnav">Mauris neque egestas justo </a></li>

						<li><a href="#" class="leftnav">Neque eros a nequestibulum </a></li>
						<li><a href="#" class="leftnav">Primis in faucibus orci luctus </a></li>
						<li><a href="#" class="leftnav">Posuere cubilia Curae </a></li>
						<li><a href="#" class="leftnav">Ulla risus risus sagittis in </a></li>
						<li><a href="#" class="leftnav">Lobortis sed tincidunt at est.</a></li>
						<li><a href="#" class="leftnav">Donec posuere egestas ipsum</a></li>

						<li><a href="#" class="leftnav">Cras ac magna vel justo </a></li>
						<li><a href="#" class="leftnav">Sollicitudin viverra. </a></li>
						<li><a href="#" class="leftnav">Nullam elementum nibh ut </a></li>
					</ul>
				</div>
			</div>
			<div id="contentmid">

				<div class="midheading"><h2>קצת מידע על הגילדה</h2></div>
				<div class="midtxt"><span class="midboldtxt">Nulla eget lacus ac duidictum ellentesque dapibus nibh ornare</span><br />volutpat, diam leo vestibulum lectus, eu molestie elit est eu ipsum. Ut accumsan nisl eu velit. Morbi eros felis, ornare sed, vestibulum cursus, vehicula et, nisl. Etiam adipiscing. </div>

				<div class="midheading"><h2>מחפש שחקן?<span class="projectheading">Wednesday, May 07, 2008</span></h2></div>
				<div id="projectbg">
					<div id="projectthumnail"></div>
					<div id="projecttxtblank">
						<div id="projecttxt"><span class="projectboldtxt">Nulla venenati sed varius an teproin</span> libero aecenas dapibus am gravida ante quis arcu liquam eleifend. Donec at elit. Integer lectus dolor utrum a volutpat.<br /></div>
						<div id="moreproject"><a href="#" class="moreproject">לפרופיל המלא</a></div>

					</div>
				</div>
				
				<div id="projectbg">
					<div id="projectthumnail"></div>
					<div id="projecttxtblank">
						<div id="projecttxt"><span class="projectboldtxt">Nulla venenati sed varius an teproin</span> libero aecenas dapibus am gravida ante quis arcu liquam eleifend. Donec at elit. Integer lectus dolor utrum a volutpat.<br /></div>
						<div id="moreproject"><a href="#" class="moreproject">לפרופיל המלא</a></div>

					</div>
				</div>
				<div class="midtxt"><span class="midboldtxt">שחקנים אלו מוצגים בצורה אקראית מתוך מאגר השחקנים</span><p>הצג שחקנים נוספים שמחפשים קבוצות</p></div>
			</div>
			<div id="contentright">
				<div class="rightheading">
					<h4>חדשות הגילדה</h4>
				</div>

				<div id="galleryblank">
					<div class="righttxt"><span class="rightboldtxt">01. aliquet tempor nisi tellus </span>bibendum nunc. Sed venenatis scelerisque ipsum.</div>

					<div class="righttxt"><span class="rightboldtxt">02. Tempor nisi tellus </span><br />Ndum nunc. Sed venenatis scelerisque ipsum.</div>
					<div class="righttxt"><span class="rightboldtxt">03. Kempor sisi vellus </span><br />Qchdum nunc. Sed venenatis scelerisque ipsum.</div>
					<div class="righttxt"><span class="rightboldtxt">04. Aliquet tempor nisi tellus </span>bibendum nunc. Sed venenatis</div>
					<div class="viewbuttonbot"><a href="#" class="view"> read more</a></div>
				</div>

			</div>
		</div>
	</div>
</div>