<div id="fb-root"></div>

<?php use GuildUser\Model\Profile,\ZfcUser\Model\User;

$row = $row ?: new User();
$games = $games ?: array();
$profile = $profile ?: new Profile();

?>
<script type="text/javascript">
window.addEvent('domready', function () {

    document.id('attribute-details-humor').addEvent('mouseover', function() {
    	ToolTip.instance(this, {
    		relativeTo: this.id,
    		autohide: true,
    		hideDelay: 150,
    		position: {position: 'centerLeft', edge: 'right'}
    	}, document.id('attribute-humour-tooltip-<?php echo $profile->getHumour() ?>')).show();
    });

    document.id('attribute-details-teamplay').addEvent('mouseover', function() {
    	ToolTip.instance(this, {
    		relativeTo: this.id,
    		autohide: true,
    		hideDelay: 150,
    		position: {position: 'centerLeft', edge: 'right'}
    	}, document.id('attribute-teamplay-tooltip-<?php echo $profile->getTeamplay() ?>')).show();
    });
    
    document.id('attribute-details-mobility').addEvent('mouseover', function() {
    	ToolTip.instance(this, {
    		relativeTo: this.id,
    		autohide: true,
    		hideDelay: 150,
    		position: {position: 'centerLeft', edge: 'right'}
    	}, document.id('attribute-mobility-tooltip-<?php echo $profile->getMobility() ?>')).show();
    });

    document.id('attribute-details-hospitality').addEvent('mouseover', function() {
    	ToolTip.instance(this, {
    		relativeTo: this.id,
    		autohide: true,
    		hideDelay: 150,
    		position: {position: 'centerLeft', edge: 'right'}
    	}, document.id('attribute-hospitality-tooltip-<?php echo $profile->getHospitality() ?>')).show();
    });

    document.id('attribute-details-strictness').addEvent('mouseover', function() {
    	ToolTip.instance(this, {
    		relativeTo: this.id,
    		autohide: true,
    		hideDelay: 150,
    		position: {position: 'centerLeft', edge: 'right'}
    	}, document.id('attribute-strictness-tooltip-<?php echo $profile->getStrictness() ?>')).show();
    });

});
</script>

<?php foreach ($tooltips as $identifier => $attribute) : ?>
<?php if (method_exists($profile, 'get'.  ucfirst($identifier))):
	$method = 'get'.  ucfirst($identifier);
	$value = $profile->$method();
	$score = $attribute['scores'][$value];
?>
<div id="attribute-<?php echo $identifier ?>-tooltip-<?php echo $value ?>" class="attribute-info tooltip-content">
	<h3><?php echo $attribute['headline'] ?>: <?php echo $value ?></h3>
	<blockquote><?php echo $score['quote'] ?></blockquote>
	<p><?php echo $score['text'] ?></p>
</div>
<?php endif ?>
<?php endforeach ?>

<div id="contentbg">
	<div id="contentblank">
		<div id="content">
			
			<div id="contentwide" class="fleft">
				<div class="column fleft content-box" >
					<h2>משחקים רשומים</h2>
					<div>
<?php foreach ($games as $game): ?>
<?php	echo $this->gameIcon($game) ?>
<?php endforeach;?>
					</div>
				</div>
					
				<div class="column fright">
					<h2>מידע אישי ותכונות</h2>
					<div id="personal-box" class="content-box">
						<div id="gravatar" class="fleft"><?php echo $this->gravatar($row->getEmail()); ?></div>
						<ul>
							<li><div><label>כינוי</label><div class="fright"><?php echo $row->getDisplayName() ?></div></div></li>
							<li><div><label>מין</label><div class="fright"><?php echo $profile->getGender() ?></div></div></li>
							<li><div><label>גיל</label><div class="fright"><?php echo floor((time() - strtotime($profile->getBirthDate()))/60/60/24/365) ?></div></div></li>
							<li><div><label>עדכון אחרון</label><div class="fright"><?php //echo substr($row->getLastLogin(), 0, strpos($row->getLastLogin(), ' ')) ?></div></div></li>
						</ul>
					</div>
					
					<div id="attributes-box" class="content-box clear">
					<h3>תכונות</h3>
					<table class="attributes-table" style="width:100%">
						<tbody>
							<tr class="attribute-humour">
								<td class="attribute-name">הומור</td>
								<td class="attribute-value"><div  class="value-bar" style="width:<?php echo ($profile->getHumour() / 5 * 100)?>%;"></div></td>
								<td class="attribute-details"><div id="attribute-details-humor" class="icon"></div>
									</td>
							</tr>
							<tr class="attribute-teamplay">
								<td class="attribute-name">חברותי</td>
								<td class="attribute-value"><div  class="value-bar" style="width:<?php echo ($profile->getTeamplay() / 5 * 100)?>%;"></div></td>
								<td class="attribute-details"><div id="attribute-details-teamplay" class="icon"></div></td>
							</tr>
							<tr class="attribute-mobility">
								<td class="attribute-name">ניידות</td>
								<td class="attribute-value"><div  class="value-bar" style="width:<?php echo ($profile->getMobility() / 5 * 100)?>%;"></div></td>
								<td class="attribute-details"><div id="attribute-details-mobility" class="icon"></div></td>
							</tr>
							<tr class="attribute-hospitality">
								<td class="attribute-name">אירוח</td>
								<td class="attribute-value"><div class="value-bar" style="width:<?php echo ($profile->getHospitality() / 5 * 100)?>%;"></div></td>
								<td class="attribute-details"><div id="attribute-details-hospitality" class="icon"></div>
									</td>
							</tr>
							<tr class="attribute-strictness">
								<td class="attribute-name">קפדנות</td>
								<td class="attribute-value"><div class="value-bar" style="width:<?php echo ($profile->getStrictness() / 5 * 100)?>%;"></div></td>
								<td class="attribute-details"><div id="attribute-details-strictness" class="icon"></div>
									</td>
							</tr>
						</tbody>
					</table>
					</div>
					<div id="bio-box" class="content-box">
					<h3>כמה מילים על עצמי</h3>
					<div id="bio-text"><?php echo nl2br($this->escapeHtml($profile->getBio()))?></div>
				</div>
				</div>
				
			</div>
			
			<div id="contentright" class="fright">
			<div class="sociable1 clearfix">
<?php if ($profile->getLfg() == 'Yes') : ?>
				<div id="lfg-box" class=""></div>
<?php endif ?>
				<ul>
					<li class="gplus-bump"><a href="https://twitter.com/share" class="twitter-share-button" data-via="theguild">Tweet</a>
						<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script></li>
					<li><g:plusone size="medium"></g:plusone>
								<script type="text/javascript">
									window.___gcfg = {lang: 'he'}; 
									(function() {
									var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
									po.src = 'https://apis.google.com/js/plusone.js';
									var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
									})();
								</script>
					</li>
					<li class="gplus-bump"><script>
						(function(d, s, id) {
						var js, fjs = d.getElementsByTagName(s)[0];
						if (d.getElementById(id)) return;
						js = d.createElement(s); js.id = id;
						js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
						fjs.parentNode.insertBefore(js, fjs);
						}(document, 'script', 'facebook-jssdk'));</script>
						<div class="fb-like" action="like" data-send="false" data-layout="button_count" data-show-faces="false"></div></li>
				</ul>
			</div>

				
				
				<div id="locations-box" class="clear">
					<h3>מיקום רצוי למשחק</h3>
					<div id="location-hasharon" class="location">
						<label>השרון</label>
					</div>
					<div id="location-telaviv" class="location">
						<label>תל אביב</label>
					</div>
				</div>
				
				<div id="new-games" class="content-box">
					<h3>מוכן ללמוד משחקים חדשים</h3>
					<ul>
					<li>אימה</li>
					<li>גיבורי על</li>
					<li>חופשיטה</li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>
