<?php use GuildUser\Model\Profile,\ZfcUser\Model\User;

$row = $row ?: new User();
$games = $games ?: array();
$profile = $profile ?: new Profile();

?>
<script type="text/javascript">
window.addEvent('domready', function () {

    document.id('attribute-details-humor').addEvent('mouseover', function() {
    	ToolTip.instance(this, {
    		relativeTo: this.id,
    		autohide: true,
    		hideDelay: 150,
    		position: {position: 'centerLeft', edge: 'right'}
    	}, document.id('attribute-humour-tooltip-2')).show();
    });

    document.id('attribute-details-teamplay').addEvent('mouseover', function() {
    	ToolTip.instance(this, {
    		relativeTo: this.id,
    		autohide: true,
    		hideDelay: 150,
    		position: {position: 'centerLeft', edge: 'right'}
    	}, document.id('attribute-teamplay-tooltip-3')).show();
    });
    
    document.id('attribute-details-mobility').addEvent('mouseover', function() {
    	ToolTip.instance(this, {
    		relativeTo: this.id,
    		autohide: true,
    		hideDelay: 150,
    		position: {position: 'centerLeft', edge: 'right'}
    	}, document.id('attribute-mobility-tooltip-3')).show();
    });

    document.id('attribute-details-hospitality').addEvent('mouseover', function() {
    	ToolTip.instance(this, {
    		relativeTo: this.id,
    		autohide: true,
    		hideDelay: 150,
    		position: {position: 'centerLeft', edge: 'right'}
    	}, document.id('attribute-hospitality-tooltip-5')).show();
    });

    document.id('attribute-details-strictness').addEvent('mouseover', function() {
    	ToolTip.instance(this, {
    		relativeTo: this.id,
    		autohide: true,
    		hideDelay: 150,
    		position: {position: 'centerLeft', edge: 'right'}
    	}, document.id('attribute-strictness-tooltip-2')).show();
    });

});
</script>
<div id="attribute-humour-tooltip-2" class="tooltip-content"><h3>דירוג הומור: 2</h3>
	<blockquote>גנום, טרול ושני גובלינים נכנסים ל... רגע, לא, מההתחלה</blockquote>
	<p>אתה לא מצחיק אבל כנראה גם לא מדכא. משחקים איתך הם משעשעים, כל עוד הכנת את הבדיחות מראש ועשית חזרות בבית.</p>
</div>
<div id="attribute-teamplay-tooltip-3" class="tooltip-content"><h3>חברותי דירוג: 3</h3>
	<blockquote>גנום, טרול ושני גובלינים נכנסים ל... רגע, לא, מההתחלה</blockquote>
	<p>אתה לא מצחיק אבל כנראה גם לא מדכא. משחקים איתך הם משעשעים, כל עוד הכנת את הבדיחות מראש ועשית חזרות בבית.</p>
</div>
<div id="attribute-mobility-tooltip-3" class="tooltip-content"><h3>דירוג ניידות: 3</h3>
	<blockquote>תרד, אני מגיע</blockquote>
	<p>אתה נייד וממונע. בין אם בכוחות קסומים, על הסוס של אבא או המכונית הפרטית,
	 אתה מסוגל להגיע לכל מקום המרחק סביר ואולי אף תיתן טרמפים עבור פיצוי הולם</p>
</div>
<div id="attribute-hospitality-tooltip-5" class="tooltip-content"><h3>דירוג אירוח: 5</h3>
<blockquote>בואו! יש פיצה ביתית!</blockquote>
<p>אם היית יכול, היית עושה מינ/מקס למטבח והסלון שלך. כל משחק אצלך הוא חגיגה של אוכל, חברה ומשחק
עד השעות הקטנות של הלילה</p>
</div>
<div id="attribute-strictness-tooltip-2" class="tooltip-content"><h3>דירוג קפדנות: 2</h3>
<blockquote>המשחק נברא כדי שיהנו ממנו</blockquote>
<p> החוקים של המשחק והמנחה לא ממש חשובים לך - הם מצע מעניין לדיונים פילוסופיים אבל הם יכולים להישרף
לפני שתיתן להם לעכב לך את המשחק או לעצור את הדמות שלך מלעשות משהו שהיא רוצה.</p>
</div>
<div id="contentbg">
	<div id="contentblank">
		<div id="content">
			
			<div id="contentwide" class="fleft">
				<div class="column fleft content-box" >
					<h2>משחקים רשומים</h2>
					<div>
<?php foreach ($games as $game): ?>
<?php	echo $this->gameIcon($game) ?>
<?php endforeach;?>
					</div>
				</div>
					
				<div class="column fright">
					<h2>מידע אישי ותכונות</h2>
					<div id="personal-box" class="content-box">
						<div id="gravatar" class="fleft"><?php echo $this->gravatar($row->getEmail()); ?></div>
						<ul>
							<li><div><label>כינוי</label><div class="fright"><?php echo $row->getDisplayName() ?></div></div></li>
							<li><div><label>מין</label><div class="fright"><?php echo $profile->getGender() ?></div></div></li>
							<li><div><label>גיל</label><div class="fright"><?php echo floor((time() - strtotime($profile->getBirthDate()))/60/60/24/365) ?></div></div></li>
							<li><div><label>עדכון אחרון</label><div class="fright"><?php //echo substr($row->getLastLogin(), 0, strpos($row->getLastLogin(), ' ')) ?></div></div></li>
						</ul>
					</div>
					
					<div id="attributes-box" class="content-box clear">
					<h3>תכונות</h3>
					<table class="attributes-table" style="width:100%">
						<tbody>
							<tr class="attribute-humour">
								<td class="attribute-name">הומור</td>
								<td class="attribute-value"><div  class="value-bar" style="width:<?php echo ($profile->getHumour() / 5 * 100)?>%;"></div></td>
								<td class="attribute-details"><div id="attribute-details-humor" class="icon"></div>
									</td>
							</tr>
							<tr class="attribute-teamplay">
								<td class="attribute-name">חברותי</td>
								<td class="attribute-value"><div  class="value-bar" style="width:<?php echo ($profile->getTeamplay() / 5 * 100)?>%;"></div></td>
								<td class="attribute-details"><div id="attribute-details-teamplay" class="icon"></div></td>
							</tr>
							<tr class="attribute-mobility">
								<td class="attribute-name">ניידות</td>
								<td class="attribute-value"><div  class="value-bar" style="width:<?php echo ($profile->getMobility() / 5 * 100)?>%;"></div></td>
								<td class="attribute-details"><div id="attribute-details-mobility" class="icon"></div></td>
							</tr>
							<tr class="attribute-hospitality">
								<td class="attribute-name">אירוח</td>
								<td class="attribute-value"><div class="value-bar" style="width:<?php echo ($profile->getHospitality() / 5 * 100)?>%;"></div></td>
								<td class="attribute-details"><div id="attribute-details-hospitality" class="icon"></div>
									</td>
							</tr>
							<tr class="attribute-strictness">
								<td class="attribute-name">קפדנות</td>
								<td class="attribute-value"><div class="value-bar" style="width:<?php echo ($profile->getStrictness() / 5 * 100)?>%;"></div></td>
								<td class="attribute-details"><div id="attribute-details-strictness" class="icon"></div>
									</td>
							</tr>
						</tbody>
					</table>
					</div>
					<div id="bio-box" class="content-box">
					<h3>כמה מילים על עצמי</h3>
					<div id="bio-text"><?php echo nl2br($this->escape($profile->getBio()))?></div>
				</div>
				</div>
				
			</div>
			
			<div id="contentright" class="fright">
				<div id="lfg-box" class="content-box">
				
				</div>
				
				
				<div id="locations-box" class="clear">
					<h3>מיקום רצוי למשחק</h3>
					<div id="location-hasharon" class="location">
						<label>השרון</label>
					</div>
					<div id="location-telaviv" class="location">
						<label>תל אביב</label>
					</div>
				</div>
				
				<div id="new-games" class="content-box">
					<h3>מוכן ללמוד משחקים חדשים</h3>
					<ul>
					<li>אימה</li>
					<li>גיבורי על</li>
					<li>חופשיטה</li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>
