<div id="contentbg">
	<div id="contentblank">
		<div id="content">
			
			<div id="contentwide" class="fleft">
<div>
<?php echo $this->gravatar($this->zfcUserIdentity()->getEmail()) ?>
שלום, <?php echo $this->zfcUserIdentity()->getDisplayName() ?>! <a href="<?php echo $this->url('zfcuser/logout') ?>">[התנתק]</a>
<div>רוצה תמונת פרופיל? הירשם ל-<a href="https://en.gravatar.com/site/signup/" target="_blank">Gravatar!</a></div>
</div>

<div id="tabs">
	<ul class="tabs">
        <li class="tab">פרטים אישיים</li>
        <li class="tab">מיקומים</li>
        <li class="tab">תכונות</li>
    </ul>
	<div class="tabs-container">
		<div id="personal-details-box" class="tab-content content-box">
			<h3>פרטים אישיים</h3>
			<?php echo $personal ?>
			<div id="result"></div>
		</div>

		<div class="tab-content content-box">
			<h3>אזורי משחק</h3>
			<ul class="no-bullets-list multiple-select form-field">
				<li><input type="checkbox" id="location[gush-dan]"/><label for="location[gush-dan]">גוש דן</label></li>
				<li><input type="checkbox" id="location[hasharon]" /><label for="location[hasharon]">השרון</label></li>
				<li><input type="checkbox" id="location[hashfela]" /><label for="location[hashfela]">השפלה</label></li>
				<li><input type="checkbox" id="location[abroad]" /><label for="location[abroad]">חו"ל</label></li>
			</ul>
		</div>

		<div id="attributes-editor" class="tab-content content-box">
			<div><h3>התכונות שלי</h3>
				<select>
				<option>בחר סט תכונות...</option>
				<option>גבר_גבר</option>
				<option>שחקן אמיתי</option>
				<option>Power Gamer</option>
				<option>מאנצ'קין</option>
				<option>עורך דין</option>
				<option>Fatbeard</option>
				</select>
			</div>

			<div id="attributes-form-box" class="content-box">
				<div id="attribute-info-box" class="content-box fright">
					<div id="attribute-humour_1" class="attribute-info tooltip">
						<div class="tooltip-content">
							<h3>דירוג הומור: 1</h3>
							<blockquote>בדיחות הדעת היא לחלשים</blockquote>
							<p>יבש כמו צנון, מרובע כמו מסך מחשב, משעמם כמו צבע מתייבש. זה לא שאין לך מחשבות מצחיקות ... הן פשוט מצחיקות רק אותך.</p>
						</div>
					</div>
					<div id="attribute-humour_2" class="attribute-info tooltip">
						<div class="tooltip-content">
							<h3>דירוג הומור: 2</h3>
							<blockquote>גנום, טרול ושני גובלינים נכנסים ל... רגע, לא, מההתחלה</blockquote>
							<p>אתה לא מצחיק אבל כנראה גם לא מדכא. משחקים איתך הם משעשעים, כל עוד הכנת את הבדיחות מראש ועשית חזרות בבית.</p>
						</div>
					</div>
					<div id="attribute-humour_3" class="attribute-info tooltip">
						<div class="tooltip-content">
							<h3>דירוג הומור: 3</h3>
							<blockquote>יש לי יש לי יש לי! פההההה!</blockquote>
							<p>צחוק בריא לנשמה - אתה יודע ומיישם. משחקים איתך הם משעשעים, עם one-liners וכמה גיחוחים וציטוטי קומדי קלאב. כשאתה מנסה לאלתר ... זה לא תמיד הולך אבל מעריכים את המאמץ!</p>
						</div>
					</div>
					<div id="attribute-humour_4" class="attribute-info tooltip">
						<div class="tooltip-content">
							<h3>דירוג הומור: 4</h3>
							<blockquote>רגע, סנונית אפריקאית? או אירופאית?</blockquote>
							<p>צחוק, בשבילך, הוא סוג של תחביב. יש לך את הניצוץ והידע כיצד להשתמש במילים כמו בחרב סייף חדה. מפגשים איתך לעיתים מסתיימים בגילגולים על הריצפה ובטן כואבת</p>
						</div>
					</div>
					<div id="attribute-humour_5" class="attribute-info tooltip">
						<div class="tooltip-content">
							<h3>דירוג הומור: 5</h3>
							<blockquote>מוה-הא-הא-הא-הא</blockquote>
							<p>אתה אלוהי הצחוק. כשאתה נכנס לחדר, נכנס יחד איתך חוש ההומור ותופס כיסא נפרד. משחקים איתך הם נושא שיחה לכמה חודשים ומאוחר בלילה, פרצי צחוק חסרי שליטה עדיין יהדהדו בבתי השחקנים האחרים</p>
						</div>
					</div>

					<div id="attribute-teamplay_1" class="attribute-info tooltip">
						<div class="tooltip-content">
							<h3>שיתוף פעולה: 1</h3>
							<blockquote>מי שאוכל לבד, אוכל יותר</blockquote>
							<p>בדד, בשבילך אינה מילה גסה. למעשה זהו מצב מועדף - אין מי שיציק עם שאלות כמו "אתה בטוח שזה יעבוד?" או יעלב אם תהרוג את הדמות שלו בשביל החלק שלו ... אה, שלך, באוצר. אם רק היה אפשר, היית נפתר מהמנחה.</p>
						</div>
					</div>
					<div id="attribute-teamplay_2" class="attribute-info tooltip">
						<div class="tooltip-content">
							<h3>שיתוף פעולה: 2</h3>
							<blockquote>אני מוכן שתהיה בסביבה שלי, אבל לא קרוב מדי</blockquote>
							<p>אנשים הם דברים שימושיים. אולי מצאת דרך לתקשר עם שחקנים אחרים אבל עדיין תעשה מה שטוב לך, ללא קשר לרצון הקבוצה. זה לא שאתה אדם רע - הם פשוט יודו לך בסוף, אם רק הם יחכו.</p>
						</div>
					</div>
					<div id="attribute-teamplay_3" class="attribute-info tooltip">
						<div class="tooltip-content">
							<h3>שיתוף פעולה: 3</h3>
							<blockquote>אם כל אחד יעשה את התפקיד שלו, הכול יהיה בסדר</blockquote>
							<p>משחקי קבוצה הם שם המשחק בשבילך. אם אתה לבד, אתה שואף לחזור ללהקה. אתה יודע את מקומך ואתה מכיר את השחקנים טוב מספיק כדי לדעת מי זה מי ולמה.</p>
						</div>
					</div>
					<div id="attribute-teamplay_4" class="attribute-info tooltip">
						<div class="tooltip-content">
							<h3>שיתוף פעולה: 4</h3>
							<blockquote>אחד בשביל כולם! כולם בשביל אחד!</blockquote>
							<p>הקבוצה גדולה מסכום חלקיה והחלקים השונים צריכים לנוע במקשה אחת ולתמוך בכל הרכיבים השונים. כאשר אנו מאוחדים, נוכל לכל אתגר!</p>
						</div>
					</div>
					<div id="attribute-teamplay_5" class="attribute-info tooltip">
						<div class="tooltip-content">
							<h3>שיתוף פעולה: 5</h3>
							<blockquote>שירותים? רגע כולנו נבוא איתך!</blockquote>
							<p>המשחקים איתך הם סוג של ניסוי חברתי בו הקבוצה כולה קשורה בכפות הרגליים במשחק
							כדורגל כנגד גמדים עם קוצים על הראש. הקבוצה לא רק יותר חשובה מהפרט, במשחק הפרט אינו קיים! </p>
						</div>
					</div>

				</div>
				<ul id="attributes-form-list" class="form-field no-bullets-list">
					<li id="attribute-humour-item"><label>הומור</label>
						<div class="slide_container fright" >
							<div class="slider" id="slider_humour" >
								<div class="slider_gutter_l slider_gutter_item"></div>
								<div id="slider_gutter_humour" class="slider_gutter_i slider_gutter_item">
									<img class="slider_bkg" src="/images/slider/bkg_slider.gif"/>
									<div class="knob"></div>
								</div>
								<div class="slider_gutter_r slider_gutter_item"> </div>
							</div>
						</div>
					</li>
					<li id="attribute-teamplay-item"><label>שיתוף פעולה</label><div class="slide_container fright" >
							<div class="slider" id="slider_teamplay" >
								<div class="slider_gutter_l slider_gutter_item"></div>
								<div id="slider_gutter_humour" class="slider_gutter_i slider_gutter_item">
									<img class="slider_bkg" src="/images/slider/bkg_slider.gif"/>
									<div class="knob"></div>
								</div>
								<div class="slider_gutter_r slider_gutter_item"> </div>
							</div>
						</div></li>
					<li><label>מנהיגות</label><span>slider</span></li>
					<li><label>יצירתיות</label><span>slider</span></li>
					<li><label>ניידות</label><span>slider</span></li>
					<li><label>מיקוד</label><span>slider</span></li>
					<li><label>אירוח</label><span>slider</span></li>
					<li><label>קפדנות</label><span>slider</span></li>
				</ul>
			</div>
		</div>
	</div>
</div>

<script type="text/javascript" >

// ON LOAD 
window.addEvent('domready', function() {
	

	new Form.Request($('personal-form'), $('result'), {
		requestOptions: {
			'spinnerTarget': $('personal-form')
		},
		extraData: { // This is just to make this example work.
			'html': 'Form sent.'
		}
	});

	
        var tabPane = new TabPane('tabs', {contentSelector: '.tab-content'}, function() {
			var showTab = window.location.hash.match(/tab=(\d+)/);
			return showTab ? showTab[1] : 0;
		});

        tabPane.addEvent('change', function(){
			// initialise the sliders if the editor is visible and was not previously initialised
			if ($('attributes-editor').isVisible() && (! $('attributes-editor').initialised)) {
				var mySlideC = new Slider($$('#attribute-humour-item .slider_gutter_i')[0],
											$$('#attribute-humour-item .knob')[0],
											$$('#attribute-humour-item img.slider_bkg')[0],{
					start: 1,
					end: 5,
					offset:0,
					snap:true, 
					numsteps:4,
					onChange: function(pos){
						$$('.attribute-info').removeClass('active');
						if ($('attribute-humour_'+pos)) {
							$('attribute-humour_'+pos).addClass('active');
						}
						
					}
				}, null).setMin(1);
				
				var mySlideC = new Slider($$('#attribute-teamplay-item .slider_gutter_i')[0],
											$$('#attribute-teamplay-item .knob')[0],
											$$('#attribute-teamplay-item img.slider_bkg')[0],{
					start: 1,
					end: 5,
					offset:0,
					snap:true, 
					numsteps:4,
					onChange: function(pos){
						$$('.attribute-info').removeClass('active');
						if ($('attribute-teamplay_'+pos)) {
							$('attribute-teamplay_'+pos).addClass('active');
						}
						
					}
				}, null).setMin(1);

				$('attributes-editor').initialised = true;
	        }
        });
});


</script>
			</div>
			<div id="contentright" class="fright">
				side panel
			</div>
		</div>
	</div>
</div>
				

