<?php $profile = $profile ?: new \GuildUser\Model\Profile() ?>
<div id="contentbg">
	<div id="contentblank">
		<div id="content">
			
			<div id="contentwide" class="fleft">
<div>
<?php echo $this->gravatar($this->zfcUserIdentity()->getEmail()) ?>
שלום, <?php echo $this->zfcUserIdentity()->getDisplayName() ?>! <a href="<?php echo $this->url('zfcuser/logout') ?>">[התנתק]</a>
</div>

<div id="tabs">
	<ul class="tabs">
        <li class="tab">פרטים אישיים</li>
        <li class="tab">משחקים</li>
        <li class="tab">אזורי משחק</li>
        <li class="tab">תכונות</li>
    </ul>
	<div class="tabs-container">
		<div id="personal-details-box" class="tab-content content-box">
			<h3>פרטים אישיים</h3>
			<?php echo $personal ?>
			<div id="result"></div>
		</div>

		<div class="tab-content content-box">
			<h3>משחקים</h3>
			
		</div>

		<div class="tab-content content-box">
			<h3>אזורי משחק</h3>
			<ul class="no-bullets-list multiple-select form-field">
				<li><input type="checkbox" id="location[gush-dan]"/><label for="location[gush-dan]">גוש דן</label></li>
				<li><input type="checkbox" id="location[hasharon]" /><label for="location[hasharon]">השרון</label></li>
				<li><input type="checkbox" id="location[hashfela]" /><label for="location[hashfela]">השפלה</label></li>
				<li><input type="checkbox" id="location[abroad]" /><label for="location[abroad]">חו"ל</label></li>
			</ul>
		</div>

		<div id="attributes-editor" class="tab-content content-box">
			<h3>התכונות שלי</h3>

			<div id="attributes-form-box" class="content-box">
				<div id="attribute-info-box" class="content-box fright">
<?php foreach ($tooltips as $identifier => $attribute) : ?>
<?php	foreach ($attribute['scores'] as $value => $score) : ?>
					<div id="attribute_<?php echo $identifier ?>-<?php echo $value ?>" class="attribute-info tooltip">
						<div class="tooltip-content">
							<h3><?php echo $attribute['headline'] ?>: <?php echo $value ?></h3>
							<blockquote><?php echo $score['quote'] ?></blockquote>
							<p><?php echo $score['text'] ?></p>
						</div>
					</div>
<?php	endforeach ?>
<?php endforeach ?>
				</div>
				<ul id="attributes-form-list" class="form-field no-bullets-list">
					<li id="attribute-humour-item"><label>הומור</label>
						<?php echo $this->slider('humour') ?>
					</li>
					<li id="attribute-teamplay-item"><label>חברותי</label>
						<?php echo $this->slider('teamplay') ?>
					</li>
					<li id="attribute-mobility-item"><label>ניידות</label>
						<?php echo $this->slider('mobility') ?>
					</li>
					<li id="attribute-hospitality-item"><label>אירוח</label>
						<?php echo $this->slider('hospitality') ?>
					</li>
					<li id="attribute-strictness-item"><label>קפדנות</label>
						<?php echo $this->slider('strictness') ?>
					</li>
					
					<?php echo $attributesForm ?>
				</ul>
			</div>
		</div>
	</div>
</div>

<script type="text/javascript" >

// ON LOAD 
window.addEvent('domready', function() {
	

	new Form.Request($('attributes-form'), null, {
		onSend: function(){
			$('attributes-attributessubmit').set('value', 'שומר תכונות...').set('disabled', true);
		},
		onComplete: function(resultNode, textNodes, args, responseText){
			$('attributes-attributessubmit').set('value', 'שמור תכונות').set('disabled', false);
			var response = eval("(" + responseText + ")");
			if (response.success) {
				
			}
		},
		requestOptions: {
			spinnerTarget: $('attributessubmit-element')
		},
		resetForm: false
	});

	new Form.Request($('personal-form'), null, {
		onSend: function(){
			$('personal-personalsubmit').set('value', 'שומר פרטים אישיים...').set('disabled', true);
		},
		onComplete: function(resultNode, textNodes, args, responseText){
			$('personal-personalsubmit').set('value', 'שמור פרטים אישיים').set('disabled', false);
			var response = eval("(" + responseText + ")");
			if (response.success) {
				
			}
		},
		requestOptions: {
			spinnerTarget: $('personalsubmit-element')
		},
		resetForm: false
	});

	
        var tabPane = new TabPane('tabs', {contentSelector: '.tab-content'}, function() {
			var showTab = window.location.hash.match(/tab=(\d+)/);
			return showTab ? showTab[1] : 0;
		});

        tabPane.addEvent('change', function(){
			// initialise the sliders if the editor is visible and was not previously initialised
			if ($('attributes-editor').isVisible() && (! $('attributes-editor').initialised)) {
				var attributes = {
					
					humour: <?php echo intval($profile->getHumour()) ?>,
					teamplay: <?php echo intval($profile->getTeamplay()) ?>,
					mobility: <?php echo intval($profile->getMobility()) ?>,
					hospitality: <?php echo intval($profile->getHospitality()) ?>,
					strictness: <?php echo intval($profile->getStrictness()) ?>
					
				};

				Object.each(attributes,
					function(score, attribute) {
						new Slider($$('#attribute-'+ attribute +'-item .slider_gutter_i')[0],
												$$('#attribute-'+ attribute +'-item .knob')[0],
												$$('#attribute-'+ attribute +'-item img.slider_bkg')[0],{
						start: 1,
						end: 5,
						offset:0,
						snap:true, 
						numsteps:4,
						onChange: function(pos){
							$$('.attribute-info').removeClass('active');
							if ($('attribute_'+ attribute +'-'+pos)) {
								$('attribute_'+ attribute +'-'+pos).addClass('active');
							}

							if ($('attributes-'+ attribute)) {
								$('attributes-'+ attribute).value = pos;
							}

						}
					}, null).setMin(score);
				});
				
				$('attributes-editor').initialised = true;
	        }
        });
});


</script>
			</div>
			<div id="contentright" class="fright">
				side panel
			</div>
		</div>
	</div>
</div>
				

